### ISSUE TITLE
Bahasa Indonesia

### ISSUE THREAD

**Issue by cintasemua** [henriyulianto/solmisasi-lily#2]
Syalom, mas.
Boleh dibuatkan tutorial dalam bahasa Indonesia?
saya udah coba berulang kali, belum mengerti cara penggunaan Solmisasi-lily ini di Lilypond/Frescobaldi.

Terima kasih
GBU

**Comment by henriyulianto** [comment]
> Syalom, mas.
> Boleh dibuatkan tutorial dalam bahasa Indonesia?
> saya udah coba berulang kali, belum mengerti cara penggunaan Solmisasi-lily ini di Lilypond/Frescobaldi.
> 
> Terima kasih
> GBU

Coba pakai google translate saja. Tutorial dalam bahasa Indonesia mungkin akan saya buat untuk versi selanjutnya. Belum ada rencana.
Oh ya, utk Lilypond versi 2.21 dst, library ini tdk dpt dipergunakan. Kalau ada waktu, akan saya kembangkan lagi agar support Lilypond versi 2.21 ke atas.

Terima kasih. GBU.
